apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
  labels:
    app: demo
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sourceHydrator:
    drySource:
      path: env/helm-guestbook-prod
      repoURL: git@github.com:argotest64/argotestapp.git
      targetRevision: HEAD
    hydrateTo:
      targetBranch: environments/production-next
    syncSource:
      path: us-east-2
      targetBranch: environments/production
  syncPolicy:
    automated: {}
